version: '3'
services:
  worker:
    image: dataset-worker
    volumes:
      - ../uploads:/uploads
      - ../outputs:/outputs
      - ../logs:/logs
    environment:
      - PROGRESS=1
    command: ["python", "-m", "dataset_pipe.pipeline.run_pipeline"]
